version: '2'
services:
  postgres:
    image: "postgres:latest"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=pass"
      - "POSTGRES_DB=employees"
    ports:
      - 5432:5432